apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyc-trip-duration
spec:
  selector:
    matchLabels:
      app: nyc-trip-duration
  template:
    metadata:
      labels:
        app: nyc-trip-duration
    spec:
      containers:
      - name: nyc-trip-duration
        image: nyc-trip-duration:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nyc-trip-duration
spec:
  selector:
    app: nyc-trip-duration
  ports:
  - port: 1234
    targetPort: 8080
