stages:
  make_dataset:
    cmd: python3 src/data/make_dataset.py /data/raw
    deps:
    - ./data/raw
    - src/data/make_dataset.py
  train_model:
    cmd: python3 src/models/train_model.py /data/processed
    deps:
    - ./data/processed
    - src/models/train_model.py
  push_model:
    cmd: python3 src/models/push_model.py
    deps:
    - src/models/push_model.py