stages:
  make_dataset:
    cmd: python .\src\data\make_dataset.py .\data\raw
    deps:
    - .\data\raw
    - .\src\data\make_dataset.py
    outs:
    - .\data\processed
  train_model:
    cmd: python .\src\models\train_model.py .\data\processed
    deps:
    - .\data\processed
    - .\src\models\train_model.py
    outs:
    - .\models